scan_timeout = 10
add_newline = false
format = """
$username\
$hostname\
$env_var\
$conda\
$custom\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$status\
$cmd_duration\
$line_break\
$jobs\
$character"""

[username]
style_user = "bold fg:black bg:yellow"
style_root = "bold fg:black bg:red"
format = "[ $user ]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "bold fg:white bg:purple"
format =  "[ $hostname ]($style)"
disabled = false

[env_var]
variable = "CUDA_VISIBLE_DEVICES"
default = ""
style = "bold fg:white bg:green"
format = "[ $env_value ]($style)"

[conda]
symbol = "🅒"
ignore_base = false
style = "bold fg:white bg:cyan"
format = "[ $symbol $environment ]($style)"

[custom.ros]
command = "echo $ROS_DISTRO $CATKIN_WS_NAME"
style = "bold fg:white bg:blue"
symbol = "🅡"
when = """ test ! -z "$ROS_DISTRO" """
format = "[ $symbol $output ]($style)"
disabled = false

[directory]
truncation_length = 4
truncate_to_repo = false
style = "fg:white bg:#3A3A3A"
read_only_style = "bg:#3A3A3A"
disabled = false
format = "[ $read_only]($read_only_style)[$path ]($style)"

[git_branch]
symbol = "🌱"
truncation_symbol = ""
style = "bold 11"
format = "[ ${symbol} $branch ]($style)"

[git_commit]

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[python]
symbol = "🐍"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\)) ]($style)'
python_binary = "python"

[cmd_duration]
style = "red"
format = "[ $duration ]($style)"