[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format =  "[$hostname](bold red) "
disabled = false

[conda]
format = "[$symbol$environment](dimmed green) "

[directory]
disabled = false

[git_branch]
symbol = "🌱 "
truncation_symbol = ""