scan_timeout = 10
add_newline = false
format = """
$username\
$hostname\
$conda\
$env_var\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$python\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[username]
style_user = "bold fg:black bg:yellow"
format = "[ $user ]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "bold fg:white bg:purple"
format =  "[ $hostname ]($style)"
disabled = false

[conda]
symbol = ""
ignore_base = false
style = "bold fg:black bg:cyan"
format = "[ $symbol$environment ]($style)"

[env_var]
variable = "CUDA_VISIBLE_DEVICES"
default = ""
style = "bold fg:white bg:blue"
format = "[ $env_value ]($style)"

[directory]
truncation_length = 4
truncate_to_repo = false
disabled = false
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ""
truncation_symbol = ""
format = "[ $symbol$branch ]($style)"

[cmd_duration]
format = "[ $duration ]($style)"